In [27]:
#KNN
#Logistic Regression
#SVM -linear, rbf,poly
#Random forest trees

# BEST PREDICTOR ALGO

# on diabetes SET


#KNN

In [28]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [29]:
dataset = pd.read_csv('diabetes.csv')
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6       92             62             32      126  32.0   
1            2      125             60             20      140  33.8   
2            0      117             80             31       53  45.2   
3            1       87             78             27       32  34.6   
4            3      116             74             15      105  26.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                      85.0   46        0  
1                      88.0   31        0  
2                      89.0   24        0  
3                     101.0   22        0  
4                     107.0   24        0

In [30]:
# data cleaning

# -> replace zeros
zero_not_accepted=['Glucose','BloodPressure','SkinThickness','BMI','Insulin']
for column in zero_not_accepted:
    dataset[column]=dataset[column].replace(0,np.NaN)
    mean = int(dataset[column].mean(skipna=True))
    dataset[column] = dataset[column].replace(np.NaN,mean)

In [31]:
#split data in features and target

features = list(dataset[:8])
X = dataset[features].values
y = dataset['Outcome'].values

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.2)

In [32]:
#feature scaling

sc_X = StandardScaler
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transorm(X_test)

TypeError: fit_transform() missing 1 required positional argument: 'X'

In [33]:
#define model
import math
k = math.sqrt(len(y_test)) #oneven getal van maken
print(k)
classifier = KNeighborsClassifier(n_neighbors=11,p=2,metric='euclidean')

8.717797887081348


In [34]:
#evaluate model

cm = confusion_matrix(y_test,y_pred)
print(cm)
print(f1_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [76, 114]

In [35]:
#Logistic Regression (linear data)

In [36]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model, datasets
from sklearn.preprocessing import PolynomialFeatures
import seaborn as sns

In [37]:
#read dataset
dataset = pd.read_csv('diabetes.csv')
dataset.head()




Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6       92             62             32      126  32.0   
1            2      125             60             20      140  33.8   
2            0      117             80             31       53  45.2   
3            1       87             78             27       32  34.6   
4            3      116             74             15      105  26.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                      85.0   46        0  
1                      88.0   31        0  
2                      89.0   24        0  
3                     101.0   22        0  
4                     107.0   24        0

In [38]:
# split in features and target
features = list(dataset[:8])
X = dataset[features].values
y = dataset['Outcome'].values

In [39]:
# train classifier

logreg = linear_model.LogisticRegression(C=1e5,solver='lbfgs')

logreg.fit(X,y)

print("coef = ", logreg.coef_)
print("intercept = ", logreg.intercept_)

coef =  [[-3.91080983e-01 -1.66564400e-01 -9.39837968e-02 -1.95140589e-01
   1.23297782e-02  4.20759573e-01 -1.05897869e-03  3.43229175e-01
   2.66142769e+01]]
intercept =  [-4.13560298]


C:\Users\Steven Verkest\miniconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [40]:
#predict

print(logreg.predict(np.array([1,150,100,30,140,30,120.0,50,0]).reshape(1,-1)))


[0]


In [41]:
#logistic Regression non-linear data

In [42]:
'''dataset = pd.read_csv('appels_non_linear.csv')
dataset.head()'''

rondheid  groenheid  appel
0         9          8      1
1        10          7      1
2         2          3      0
3         1          2      0
4         5          8      1

In [43]:
'''features = list(dataset[:dataset.columns.size-1])
X = dataset[features].values
y = dataset['appel'].values'''

In [44]:
#train logistic regression classifier

In [45]:
logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(X,y)

print(logreg.coef_)
print(logreg.intercept_)

[[ 0.39846303  0.49123403 19.93238954]]
[-14.639467]


In [46]:
#hogere orde logistic regression classifier

In [47]:
# Aanmaken van de hogere orde features
graad = 3

poly = PolynomialFeatures(graad)
Xp = poly.fit_transform(X)


In [48]:
# Train model op hogere orde features

logreg_poly = linear_model.LogisticRegression(C=1)
logreg_poly.fit(Xp, y)

h = 0.02

rond_min = X[:,0].min()-2
rond_max = X[:,0].max()+2

groen_min = X[:,1].min()-2
groen_max = X[:,1].max()+2


xx, yy = np.meshgrid(np.arange(rond_min, rond_max, h),np.arange(groen_min, groen_max, h))

X_m = np.hstack((xx.reshape(-1,1),yy.reshape(-1,1)))
 

X_mf = poly.fit_transform(X_m)
print(X_mf.shape)
Z = logreg_poly.predict(X_mf)
Z = Z.reshape(xx.shape)


(357500, 10)


C:\Users\Steven Verkest\miniconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


ValueError: X has 10 features per sample; expecting 20

In [49]:
#evaluate model

cm = confusion_matrix(y_test,y_pred)
print(cm)
print(f1_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [76, 114]

In [50]:
#SVM

In [51]:
# read dataset
dataset = pd.read_csv("diabetes.csv")
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6       92             62             32      126  32.0   
1            2      125             60             20      140  33.8   
2            0      117             80             31       53  45.2   
3            1       87             78             27       32  34.6   
4            3      116             74             15      105  26.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                      85.0   46        0  
1                      88.0   31        0  
2                      89.0   24        0  
3                     101.0   22        0  
4                     107.0   24        0

In [52]:
# features and target
features = list(dataset[:8])
X = dataset[features].values
y = dataset['Outcome'].values

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=0)


In [53]:
#normalisatie vd dataset
scaler = preprocessing.StandardScaler().fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [55]:
# Train een SVM via random search

from sklearn.model_selection import RandomizedSearchCV
# distributions
from scipy.stats import randint 
from scipy.stats import uniform



model = SVC()
parameters = {'kernel': ['linear','rbf','poly'],
              'C': uniform(0.01, 20), # haal C uit een random uniform distribution
              'gamma': uniform(0.001, 0.2)}


n_iter_search = 20


random_search = RandomizedSearchCV(model, param_distributions=parameters,cv=5,n_iter=n_iter_search,n_jobs = -1,verbose=1)

random_search = random_search.fit(X_train, y_train)

best_accuracy = random_search.best_score_ 
best_parameters = random_search.best_params_  

print('Best accuracy : ', random_search.best_score_)
print('Best parameters :',random_search.best_params_  )

y_pred = random_search.predict(X_test)
print(classification_report(y_test, y_pred))

cf = confusion_matrix(y_test, y_pred)
print(cf)
print(accuracy_score(y_test, y_pred) * 100) 



Fitting 5 folds for each of 20 candidates, totalling 100 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Best accuracy :  1.0
Best parameters : {'C': 18.372425447211132, 'gamma': 0.02251365751514387, 'kernel': 'rbf'}
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        48
           1       1.00      1.00      1.00        28

    accuracy                           1.00        76
   macro avg       1.00      1.00      1.00        76
weighted avg       1.00      1.00      1.00        76

[[48  0]
 [ 0 28]]
100.0


[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    1.4s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:    1.5s finished


In [ ]:
# Random Forest Trees

In [1]:
#import libs
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import linear_model

from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

from sklearn import linear_model, datasets
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn import preprocessing

from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
import seaborn as sns


In [2]:
#read data

dataset = pd.read_csv('diabetes.csv')

In [3]:
# split in features and target
features = list(dataset[:8])
X = dataset[features].values
y = dataset['Outcome'].values

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [5]:
#random forest classifier

number_of_trees = 1000
max_number_of_features = 2

RFCmodel = RandomForestClassifier(n_estimators = number_of_trees,max_features=max_number_of_features)
RFCmodel.fit(X_train,y_train)

print(RFCmodel.feature_importances_)

[0.03519144 0.13260928 0.0170686  0.03176101 0.07420514 0.03630588
 0.03957272 0.05463667 0.57864927]


In [7]:
# Test Random Forest Classifier

y_pred = RFCmodel.predict(X_test)

print(classification_report(y_test, y_pred))

cf = confusion_matrix(y_test, y_pred)
print(cf)
print(accuracy_score(y_test, y_pred) * 100) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        72
           1       1.00      1.00      1.00        42

    accuracy                           1.00       114
   macro avg       1.00      1.00      1.00       114
weighted avg       1.00      1.00      1.00       114

[[72  0]
 [ 0 42]]
100.0


In [8]:
# Bagging met logistic regression

number_of_estimators = 100
complexity = 10
cart = LogisticRegression(C=complexity,solver='liblinear')


lregbagging = BaggingClassifier(base_estimator=cart, n_estimators=number_of_estimators)

lregbagging.fit(X_train,y_train)


y_pred = lregbagging.predict(X_test)

print(classification_report(y_test, y_pred))

cf = confusion_matrix(y_test, y_pred)
print(cf)
print(accuracy_score(y_test, y_pred) * 100) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        72
           1       1.00      1.00      1.00        42

    accuracy                           1.00       114
   macro avg       1.00      1.00      1.00       114
weighted avg       1.00      1.00      1.00       114

[[72  0]
 [ 0 42]]
100.0


In [9]:
# Adaboost

clf_adaboost = AdaBoostClassifier(n_estimators=150,learning_rate=0.9)
clf_adaboost.fit(X_train,y_train)

y_pred = clf_adaboost.predict(X_test)

print(classification_report(y_test, y_pred))

cf = confusion_matrix(y_test, y_pred)
print(cf)
print(accuracy_score(y_test, y_pred) * 100) 


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        72
           1       1.00      1.00      1.00        42

    accuracy                           1.00       114
   macro avg       1.00      1.00      1.00       114
weighted avg       1.00      1.00      1.00       114

[[72  0]
 [ 0 42]]
100.0


In [10]:
# Adaboost met logistic regression classifier

cart = LogisticRegression(C=complexity,solver='liblinear')
logreg_adaboost = AdaBoostClassifier(base_estimator=cart,n_estimators=150,learning_rate=0.9) 
logreg_adaboost.fit(X_train,y_train)

y_pred = logreg_adaboost.predict(X_test)

print(classification_report(y_test, y_pred))

cf = confusion_matrix(y_test, y_pred)
print(cf)
print(accuracy_score(y_test, y_pred) * 100) 


              precision    recall  f1-score   support

           0       0.95      0.99      0.97        72
           1       0.97      0.90      0.94        42

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

[[71  1]
 [ 4 38]]
95.6140350877193


In [11]:
# Gradient boosting

clf_gradientboost = GradientBoostingClassifier(n_estimators=150,learning_rate=0.8)

clf_gradientboost.fit(X_train,y_train)


y_pred = clf_gradientboost.predict(X_test)

print(classification_report(y_test, y_pred))

cf = confusion_matrix(y_test, y_pred)
print(cf)
print(accuracy_score(y_test, y_pred) * 100) 



              precision    recall  f1-score   support

           0       1.00      1.00      1.00        72
           1       1.00      1.00      1.00        42

    accuracy                           1.00       114
   macro avg       1.00      1.00      1.00       114
weighted avg       1.00      1.00      1.00       114

[[72  0]
 [ 0 42]]
100.0


In [12]:
#### Classificatie met XGBoost

from xgboost import XGBClassifier

clf_xgb = XGBClassifier(n_estimators=150)
clf_xgb.fit(X_train,y_train)

y_pred = clf_xgb.predict(X_test)

print(classification_report(y_test, y_pred))

cf = confusion_matrix(y_test, y_pred)
print(cf)
print(accuracy_score(y_test, y_pred) * 100) 


ModuleNotFoundError: No module named 'xgboost'